### ISSUE TITLE
Improve Layout Alignment for Contributor Cards

### ISSUE THREAD

**Issue by D-Binara** [D-Binara/The-Weaver-s-Gift#8]
The current layout of the Contributors page can be enhanced to improve visual consistency and user experience. The contributor cards appear slightly unbalanced, especially on larger or smaller screens. Adjustments should be made to ensure the cards are well-positioned within the viewport, providing a clean and uniform look across all devices.

**Comment by ChaudaryHammad** [comment]
Hi, @D-Binara assign it to me. I can do this.

**Comment by D-Binara** [comment]
Thank you, @ChaudaryHammad, for the excellent work on fixing the layout! Everything looks great now. Closing this issue.
